### ISSUE TITLE
Support for blank NetCDF Global Attributes

### ISSUE THREAD

**Issue by LupusUmbrae** [senbox-org/s3tbx#11]
Could you add support for handling NetCDF Global attributes that have no value, currently i get the following error:

```
java.lang.IllegalArgumentException: [data] is null
	at org.esa.snap.core.util.Guardian.assertNotNull(Guardian.java:67)
	at org.esa.snap.core.datamodel.DataNode.<init>(DataNode.java:71)
	at org.esa.snap.core.datamodel.MetadataAttribute.<init>(MetadataAttribute.java:38)
	at org.esa.s3tbx.dataio.s3.util.S3NetcdfReader.addGlobalMetadata(S3NetcdfReader.java:146)
	at org.esa.s3tbx.dataio.s3.util.S3NetcdfReader.readProduct(S3NetcdfReader.java:56)
	at org.esa.s3tbx.dataio.s3.slstr.SlstrProductFactory.readProduct(SlstrProductFactory.java:191)
	at org.esa.s3tbx.dataio.s3.AbstractProductFactory.readProducts(AbstractProductFactory.java:355)
	at org.esa.s3tbx.dataio.s3.AbstractProductFactory.createProduct(AbstractProductFactory.java:117)
	at org.esa.s3tbx.dataio.s3.Sentinel3ProductReader.createProduct(Sentinel3ProductReader.java:92)
	at org.esa.s3tbx.dataio.s3.Sentinel3ProductReader.readProductNodesImpl(Sentinel3ProductReader.java:80)
	at org.esa.snap.core.dataio.AbstractProductReader.readProductNodes(AbstractProductReader.java:169)
	at org.esa.snap.core.dataio.ProductIO.readProduct(ProductIO.java:158)
	at org.esa.snap.rcp.actions.file.ReadProductOperation.run(ReadProductOperation.java:37)
	at org.netbeans.modules.progress.ui.RunOffEDTImpl$3.run(RunOffEDTImpl.java:275)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1423)
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
```

Additionally is there a particular reason for no logging at all in the code? The lack of logging can make understanding what the error means and where it comes from quite complex (without checking out and running the application in debug).This is especially true with Sentinel 3 data where you are opening a folder containing more than 100 files the above error message makes it impossible to know which file/global attribute is in error without inspecting the code and then inspecting each of the files.

Thanks,
Robin

**Comment by LupusUmbrae** [comment]
Using version 4.0.0, upgrading this morning

**Comment by LupusUmbrae** [comment]
Odd, i modified out NetCDF files to have all global attributes filled with a value but still get the above error;

ncdump:
```
netcdf geodetic_tx {
dimensions:
	columns = 37 ;
	rows = 2700 ;
	orphan_pixels = UNLIMITED ; // (0 currently)
variables:
	double latitude_tx(rows, columns) ;
		latitude_tx:standard_name = "latitude" ;
		latitude_tx:long_name = "Latitude of detector FOV centre on the earth\'s surface" ;
		latitude_tx:units = "degrees_north" ;
	double longitude_tx(rows, columns) ;
		longitude_tx:standard_name = "longitude" ;
		longitude_tx:long_name = "Longitude of detector FOV centre on the earth\'s surface" ;
		longitude_tx:units = "degrees_east" ;

// global attributes:
		:Conventions = "NetCDF" ;
		:title = "AT SLSTR-Like L1 Radiance and Brightness Temperatures Product. (Measurements + Annotations)" ;
		:institution = "TVUK" ;
		:source = "Test" ;
		:history = "Test" ;
		:comment = "Test" ;
		:references = "Test" ;
		:contact = "Test" ;
		:netCDF_version = "netCDF 4.4.0" ;
		:product_type = "NetCDF" ;
		:product_name = "unset" ;
		:creation_time = "1468243167476" ;
		:validity_start_time = "0000-00-00T00:00:00.000000" ;
		:validity_stop_time = "0000-00-00T00:00:00.000000" ;
		:resolution = "[16000 16000]" ;
		:start_offset = 0. ;
		:track_offset = 0. ;
		:absolute_orbit_number = 0LL ;
}
```

SNAP Error:
```
java.lang.IllegalArgumentException: [data] is null
	at org.esa.snap.core.util.Guardian.assertNotNull(Guardian.java:67)
	at org.esa.snap.core.datamodel.DataNode.<init>(DataNode.java:71)
	at org.esa.snap.core.datamodel.MetadataAttribute.<init>(MetadataAttribute.java:38)
	at org.esa.s3tbx.dataio.s3.util.S3NetcdfReader.addGlobalMetadata(S3NetcdfReader.java:146)
	at org.esa.s3tbx.dataio.s3.util.S3NetcdfReader.readProduct(S3NetcdfReader.java:56)
	at org.esa.s3tbx.dataio.s3.slstr.SlstrProductFactory.readProduct(SlstrProductFactory.java:191)
	at org.esa.s3tbx.dataio.s3.AbstractProductFactory.readProducts(AbstractProductFactory.java:355)
	at org.esa.s3tbx.dataio.s3.AbstractProductFactory.createProduct(AbstractProductFactory.java:117)
	at org.esa.s3tbx.dataio.s3.Sentinel3ProductReader.createProduct(Sentinel3ProductReader.java:92)
	at org.esa.s3tbx.dataio.s3.Sentinel3ProductReader.readProductNodesImpl(Sentinel3ProductReader.java:80)
	at org.esa.snap.core.dataio.AbstractProductReader.readProductNodes(AbstractProductReader.java:169)
	at org.esa.snap.core.dataio.ProductIO.readProduct(ProductIO.java:158)
	at org.esa.snap.rcp.actions.file.ReadProductOperation.run(ReadProductOperation.java:37)
	at org.netbeans.modules.progress.ui.RunOffEDTImpl$3.run(RunOffEDTImpl.java:275)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1423)
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
```

**Comment by LupusUmbrae** [comment]
I modified the reader to give more details on the error, i simply added a try/catch inside the addGlobalMetadata loop so i could get additional information about the product and global attribute that its report is null

```
java.lang.IllegalArgumentException: Error reading Global Attribute (absolute_orbit_number) from (geodetic_tx), error is: [data] is null
	at org.esa.s3tbx.dataio.s3.util.S3NetcdfReader.addGlobalMetadata(S3NetcdfReader.java:150)
```

But from the previous comment we can see in the ncdump `:absolute_orbit_number = 0LL ;`, which is not null (or blank) value.

**Comment by LupusUmbrae** [comment]
Another developer i work with looked into this and the issue is with the data types, the 0LL datatype was not supported.

After modifying the code to support that additional data type the error went away

**Comment by marpet** [comment]
Is such a product already available where the absolute_orbit_number is 64bit integer. Currently I see only 32bit uint.
Would be good for testing.

**Comment by LupusUmbrae** [comment]
Sorry for my slowness in replying, I've sent you some sample data to work with. Hopefully that will help
