### ISSUE TITLE
IllegalArgumentException reading SLSTR product

### ISSUE THREAD

**Issue by LupusUmbrae** [senbox-org/s3tbx#9]
Hello,

Testing freshly generated SLSTR-Like products and we're getting the following exception in the SNAP logs, this seems similar to a previous issue i had reading [NetCDF files](https://github.com/senbox-org/snap-engine/issues/50).

```
java.lang.IllegalArgumentException: [type] is an empty string
	at org.esa.snap.core.util.Guardian.assertNonEmptyString(Guardian.java:326)
	at org.esa.snap.core.util.Guardian.assertNotNullOrEmpty(Guardian.java:89)
	at org.esa.snap.core.datamodel.Product.<init>(Product.java:281)
	at org.esa.snap.core.datamodel.Product.<init>(Product.java:248)
	at org.esa.snap.core.datamodel.Product.<init>(Product.java:234)
	at org.esa.s3tbx.dataio.s3.util.S3NetcdfReader.readProduct(S3NetcdfReader.java:54)
	at org.esa.s3tbx.dataio.s3.slstr.SlstrProductFactory.readProduct(SlstrProductFactory.java:191) 
```

Regards,
Robin

**Comment by marpet** [comment]
Where can I find such new products? On the ACRI ftp server or at the expert hub?

**Comment by marpet** [comment]
This would be good. I can try to blindly fix this. I guess I know why it happens but it would be good to be sure. You can send me a mail (marco.peters@brockmann-consult.de) with a private link.

**Comment by marpet** [comment]
Should be solved by: https://github.com/senbox-org/s3tbx/commit/7b89aeb35f23e22437835f50e76bcc12c33070bf
